package domain;

// Generated Aug 12, 2013 2:56:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GwAction generated by hbm2java
 */
@Entity
@Table(name = "gw_action", catalog = "genericworkflow")
public class Action implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<NodeAction> gwNodeActions = new HashSet<NodeAction>(0);

	public Action() {
	}

	public Action(String name) {
		this.name = name;
	}

	public Action(String name, Set<NodeAction> gwNodeActions) {
		this.name = name;
		this.gwNodeActions = gwNodeActions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gwAction")
	public Set<NodeAction> getGwNodeActions() {
		return this.gwNodeActions;
	}

	public void setGwNodeActions(Set<NodeAction> gwNodeActions) {
		this.gwNodeActions = gwNodeActions;
	}

}
