package domain;

// Generated Aug 12, 2013 2:56:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GwNodeAction generated by hbm2java
 */
@Entity
@Table(name = "gw_node_action", catalog = "genericworkflow")
public class NodeAction implements java.io.Serializable {

	private Integer id;
	private Node gwNode;
	private Action gwAction;
	private String fctName;
	private Boolean direction;
	private Set<WorkflowLog> gwWorkflowLogs = new HashSet<WorkflowLog>(0);

	public NodeAction() {
	}

	public NodeAction(Node gwNode, Action gwAction) {
		this.gwNode = gwNode;
		this.gwAction = gwAction;
	}

	public NodeAction(Node gwNode, Action gwAction, String fctName,
			Boolean direction, Set<WorkflowLog> gwWorkflowLogs) {
		this.gwNode = gwNode;
		this.gwAction = gwAction;
		this.fctName = fctName;
		this.direction = direction;
		this.gwWorkflowLogs = gwWorkflowLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node", nullable = false)
	public Node getGwNode() {
		return this.gwNode;
	}

	public void setGwNode(Node gwNode) {
		this.gwNode = gwNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "action", nullable = false)
	public Action getGwAction() {
		return this.gwAction;
	}

	public void setGwAction(Action gwAction) {
		this.gwAction = gwAction;
	}

	@Column(name = "fct_name", length = 45)
	public String getFctName() {
		return this.fctName;
	}

	public void setFctName(String fctName) {
		this.fctName = fctName;
	}

	@Column(name = "direction")
	public Boolean getDirection() {
		return this.direction;
	}

	public void setDirection(Boolean direction) {
		this.direction = direction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gwNodeAction")
	public Set<WorkflowLog> getGwWorkflowLogs() {
		return this.gwWorkflowLogs;
	}

	public void setGwWorkflowLogs(Set<WorkflowLog> gwWorkflowLogs) {
		this.gwWorkflowLogs = gwWorkflowLogs;
	}

}
