package domain;

// Generated Aug 12, 2013 2:56:13 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GwNodeAction generated by hbm2java
 */
@Entity
@Table(name = "gw_node_action", catalog = "genericworkflow")
public class NodeAction implements java.io.Serializable {

	private Integer id;
	private Node node;
	private Action action;
	private String fctName;
	private Boolean direction;

	public NodeAction() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node", nullable = false)
	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "action", nullable = false)
	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	@Column(name = "fct_name", length = 45)
	public String getFctName() {
		return this.fctName;
	}

	public void setFctName(String fctName) {
		this.fctName = fctName;
	}

	@Column(name = "direction")
	public Boolean getDirection() {
		return this.direction;
	}

	public void setDirection(Boolean direction) {
		this.direction = direction;
	}
}
